import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Define the Geist font family for general text with specific configurations.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata object to configure the basic information of the HTML page.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// The RootLayout component: The main layout wrapper for the entire application.
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`bg-secondary text-primary ${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
